// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjSO7pwLKPcjbE9Jzoe5ycvYv3zbcl2WQ',
    appId: '1:398975033410:web:26704019e4e12a39cf0ddb',
    messagingSenderId: '398975033410',
    projectId: 'clothes-9af86',
    authDomain: 'clothes-9af86.firebaseapp.com',
    databaseURL: 'https://clothes-9af86-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'clothes-9af86.appspot.com',
    measurementId: 'G-GVEXNT7BBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxXgNE9bHZwiRVN6NEIPgtq-C_AI17Jcg',
    appId: '1:398975033410:android:c4a847a9bbf529cacf0ddb',
    messagingSenderId: '398975033410',
    projectId: 'clothes-9af86',
    databaseURL: 'https://clothes-9af86-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'clothes-9af86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFOTlqpRy8Rhye89K39Nsu_yFBEHPShFw',
    appId: '1:398975033410:ios:071918ce46a8441dcf0ddb',
    messagingSenderId: '398975033410',
    projectId: 'clothes-9af86',
    databaseURL: 'https://clothes-9af86-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'clothes-9af86.appspot.com',
    iosBundleId: 'com.example.clothes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFOTlqpRy8Rhye89K39Nsu_yFBEHPShFw',
    appId: '1:398975033410:ios:071918ce46a8441dcf0ddb',
    messagingSenderId: '398975033410',
    projectId: 'clothes-9af86',
    databaseURL: 'https://clothes-9af86-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'clothes-9af86.appspot.com',
    iosBundleId: 'com.example.clothes',
  );
}
